export const ActionTypes = {
    //LANGUAGE
    SET_LANGUAGE: 'SET_LANGUAGE',

    //PRODUCT
    SET_PRODUCT: "SET_PRODUCT",
    SET_PRODUCT_FAVERITE: "SET_PRODUCT_FAVERITE",
    SET_PRODUCT_CHEAP: "SET_PRODUCT_CHEAP",
    SET_PRODUCT_EXPENSIVE: "SET_PRODUCT_EXPENSIVE",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    // NEW
    SET_NEWS: "SET_NEWS",
    SET_NEWS_TIPS: " SET_NEWS_TIPS",
    SET_NEWS_EXPERIENCE: "SET_NEWS_EXPERIENCE",
    SET_NEWS_MANY: " SET_NEWS_MANY",
    SELECTED_NEWS: "SELECTED_NEWS",
    REMOVE_SET_NEWS: "REMOVE_SET_NEWS",

    SET_PAYMENT: "SET_PAYMENT",
    SET_ACCOUNT: "SET_ACCOUNT",

    SET_ID_PRODUCT: " SET_ID_PRODUCT",

}

